apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'yasindudoc@gmail.com'
      smtp_auth_username: 'yasindudoc@gmail.com'
      smtp_auth_password: 'duwhgjyjlncivnfw' 
      smtp_require_tls: true

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'email-notifications'

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'yasindudoc@gmail.com' 
        send_resolved: true
        html: '{{ template "email.default.html" . }}'