apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: salon-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: salon-service
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s