spring:
  application:
    name: payment-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?
    username: root
    password: yasindusql
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8085


stripe:
  api:
    key: ${STRIPE_PUBLISHABLE_KEY}
    secret: ${STRIPE_SECRET_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8761/eureka/"