spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql:3306/userdb?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:yasindusql}
    driver-class-name: com.mysql.cj.jdbc.Driver