apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: salon-db
spec:
  serviceName: salon-db
  replicas: 1
  selector:
    matchLabels:
      app: salon-db
  template:
    metadata:
      labels:
        app: salon-db
    spec:
      nodeSelector:
        node-role: salon-worker
      containers:
        - name: salon-db
          image: mysql:8.0
          ports:
            - containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: salon-db-secret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: salon-db-storage
              mountPath: /var/lib/mysql

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

  volumeClaimTemplates:
    - metadata:
        name: salon-db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi